//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webszolg.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrenciesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrenciesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrenciesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrenciesResult {
            get {
                return this.GetCurrenciesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrenciesResultField, value) != true)) {
                    this.GetCurrenciesResultField = value;
                    this.RaisePropertyChanged("GetCurrenciesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrencyUnitsResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrencyUnitsResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrencyUnitsResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrencyUnitsResult {
            get {
                return this.GetCurrencyUnitsResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrencyUnitsResultField, value) != true)) {
                    this.GetCurrencyUnitsResultField = value;
                    this.RaisePropertyChanged("GetCurrencyUnitsResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetCurrentExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetCurrentExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetCurrentExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetCurrentExchangeRatesResult {
            get {
                return this.GetCurrentExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetCurrentExchangeRatesResultField, value) != true)) {
                    this.GetCurrentExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetCurrentExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDateIntervalResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetDateIntervalResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetDateIntervalResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetDateIntervalResult {
            get {
                return this.GetDateIntervalResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetDateIntervalResultField, value) != true)) {
                    this.GetDateIntervalResultField = value;
                    this.RaisePropertyChanged("GetDateIntervalResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNamesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((object.ReferenceEquals(this.startDateField, value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((object.ReferenceEquals(this.endDateField, value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string currencyNames {
            get {
                return this.currencyNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNamesField, value) != true)) {
                    this.currencyNamesField = value;
                    this.RaisePropertyChanged("currencyNames");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetExchangeRatesResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetExchangeRatesResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetExchangeRatesResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetExchangeRatesResult {
            get {
                return this.GetExchangeRatesResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetExchangeRatesResultField, value) != true)) {
                    this.GetExchangeRatesResultField = value;
                    this.RaisePropertyChanged("GetExchangeRatesResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoRequestBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoRequestBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInfoResponseBody", Namespace="http://www.mnb.hu/webservices/")]
    [System.SerializableAttribute()]
    public partial class GetInfoResponseBody : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetInfoResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string GetInfoResult {
            get {
                return this.GetInfoResultField;
            }
            set {
                if ((object.ReferenceEquals(this.GetInfoResultField, value) != true)) {
                    this.GetInfoResultField = value;
                    this.RaisePropertyChanged("GetInfoResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mnb.hu/webservices/", ConfigurationName="ServiceReference1.MNBArfolyamServiceSoap")]
    public interface MNBArfolyamServiceSoap {
        
        // CODEGEN: Generating message contract since the operation GetCurrencies is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        webszolg.ServiceReference1.GetCurrenciesResponse GetCurrencies(webszolg.ServiceReference1.GetCurrenciesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencies", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrenciesResponse")]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrenciesResponse> GetCurrenciesAsync(webszolg.ServiceReference1.GetCurrenciesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrencyUnits is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        webszolg.ServiceReference1.GetCurrencyUnitsResponse GetCurrencyUnits(webszolg.ServiceReference1.GetCurrencyUnitsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnits", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrencyUnitsResponse")]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(webszolg.ServiceReference1.GetCurrencyUnitsRequest request);
        
        // CODEGEN: Generating message contract since the operation GetCurrentExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesStrin" +
            "gFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        webszolg.ServiceReference1.GetCurrentExchangeRatesResponse GetCurrentExchangeRates(webszolg.ServiceReference1.GetCurrentExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetCurrentExchangeRatesRespo" +
            "nse")]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(webszolg.ServiceReference1.GetCurrentExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetDateInterval is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        webszolg.ServiceReference1.GetDateIntervalResponse GetDateInterval(webszolg.ServiceReference1.GetDateIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateInterval", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetDateIntervalResponse")]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetDateIntervalResponse> GetDateIntervalAsync(webszolg.ServiceReference1.GetDateIntervalRequest request);
        
        // CODEGEN: Generating message contract since the operation GetExchangeRates is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        webszolg.ServiceReference1.GetExchangeRatesResponse GetExchangeRates(webszolg.ServiceReference1.GetExchangeRatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRates", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetExchangeRatesResponse")]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetExchangeRatesResponse> GetExchangeRatesAsync(webszolg.ServiceReference1.GetExchangeRatesRequest request);
        
        // CODEGEN: Generating message contract since the operation GetInfo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoStringFault", Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        webszolg.ServiceReference1.GetInfoResponse GetInfo(webszolg.ServiceReference1.GetInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfo", ReplyAction="http://www.mnb.hu/webservices/MNBArfolyamServiceSoap/GetInfoResponse")]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetInfoResponse> GetInfoAsync(webszolg.ServiceReference1.GetInfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetCurrenciesRequestBody GetCurrencies;
        
        public GetCurrenciesRequest() {
        }
        
        public GetCurrenciesRequest(webszolg.ServiceReference1.GetCurrenciesRequestBody GetCurrencies) {
            this.GetCurrencies = GetCurrencies;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrenciesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrenciesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetCurrenciesResponseBody GetCurrenciesResponse1;
        
        public GetCurrenciesResponse() {
        }
        
        public GetCurrenciesResponse(webszolg.ServiceReference1.GetCurrenciesResponseBody GetCurrenciesResponse1) {
            this.GetCurrenciesResponse1 = GetCurrenciesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetCurrencyUnitsRequestBody GetCurrencyUnits;
        
        public GetCurrencyUnitsRequest() {
        }
        
        public GetCurrencyUnitsRequest(webszolg.ServiceReference1.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            this.GetCurrencyUnits = GetCurrencyUnits;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrencyUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrencyUnitsResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1;
        
        public GetCurrencyUnitsResponse() {
        }
        
        public GetCurrencyUnitsResponse(webszolg.ServiceReference1.GetCurrencyUnitsResponseBody GetCurrencyUnitsResponse1) {
            this.GetCurrencyUnitsResponse1 = GetCurrencyUnitsResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates;
        
        public GetCurrentExchangeRatesRequest() {
        }
        
        public GetCurrentExchangeRatesRequest(webszolg.ServiceReference1.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            this.GetCurrentExchangeRates = GetCurrentExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1;
        
        public GetCurrentExchangeRatesResponse() {
        }
        
        public GetCurrentExchangeRatesResponse(webszolg.ServiceReference1.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRatesResponse1) {
            this.GetCurrentExchangeRatesResponse1 = GetCurrentExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetDateIntervalRequestBody GetDateInterval;
        
        public GetDateIntervalRequest() {
        }
        
        public GetDateIntervalRequest(webszolg.ServiceReference1.GetDateIntervalRequestBody GetDateInterval) {
            this.GetDateInterval = GetDateInterval;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDateIntervalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDateIntervalResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetDateIntervalResponseBody GetDateIntervalResponse1;
        
        public GetDateIntervalResponse() {
        }
        
        public GetDateIntervalResponse(webszolg.ServiceReference1.GetDateIntervalResponseBody GetDateIntervalResponse1) {
            this.GetDateIntervalResponse1 = GetDateIntervalResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetExchangeRatesRequestBody GetExchangeRates;
        
        public GetExchangeRatesRequest() {
        }
        
        public GetExchangeRatesRequest(webszolg.ServiceReference1.GetExchangeRatesRequestBody GetExchangeRates) {
            this.GetExchangeRates = GetExchangeRates;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExchangeRatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExchangeRatesResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetExchangeRatesResponseBody GetExchangeRatesResponse1;
        
        public GetExchangeRatesResponse() {
        }
        
        public GetExchangeRatesResponse(webszolg.ServiceReference1.GetExchangeRatesResponseBody GetExchangeRatesResponse1) {
            this.GetExchangeRatesResponse1 = GetExchangeRatesResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetInfoRequestBody GetInfo;
        
        public GetInfoRequest() {
        }
        
        public GetInfoRequest(webszolg.ServiceReference1.GetInfoRequestBody GetInfo) {
            this.GetInfo = GetInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoResponse", Namespace="http://www.mnb.hu/webservices/", Order=0)]
        public webszolg.ServiceReference1.GetInfoResponseBody GetInfoResponse1;
        
        public GetInfoResponse() {
        }
        
        public GetInfoResponse(webszolg.ServiceReference1.GetInfoResponseBody GetInfoResponse1) {
            this.GetInfoResponse1 = GetInfoResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MNBArfolyamServiceSoapChannel : webszolg.ServiceReference1.MNBArfolyamServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MNBArfolyamServiceSoapClient : System.ServiceModel.ClientBase<webszolg.ServiceReference1.MNBArfolyamServiceSoap>, webszolg.ServiceReference1.MNBArfolyamServiceSoap {
        
        public MNBArfolyamServiceSoapClient() {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MNBArfolyamServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webszolg.ServiceReference1.GetCurrenciesResponse webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetCurrencies(webszolg.ServiceReference1.GetCurrenciesRequest request) {
            return base.Channel.GetCurrencies(request);
        }
        
        public webszolg.ServiceReference1.GetCurrenciesResponseBody GetCurrencies(webszolg.ServiceReference1.GetCurrenciesRequestBody GetCurrencies1) {
            webszolg.ServiceReference1.GetCurrenciesRequest inValue = new webszolg.ServiceReference1.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies1;
            webszolg.ServiceReference1.GetCurrenciesResponse retVal = ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetCurrencies(inValue);
            return retVal.GetCurrenciesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrenciesResponse> webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetCurrenciesAsync(webszolg.ServiceReference1.GetCurrenciesRequest request) {
            return base.Channel.GetCurrenciesAsync(request);
        }
        
        public System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrenciesResponse> GetCurrenciesAsync(webszolg.ServiceReference1.GetCurrenciesRequestBody GetCurrencies) {
            webszolg.ServiceReference1.GetCurrenciesRequest inValue = new webszolg.ServiceReference1.GetCurrenciesRequest();
            inValue.GetCurrencies = GetCurrencies;
            return ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetCurrenciesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webszolg.ServiceReference1.GetCurrencyUnitsResponse webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetCurrencyUnits(webszolg.ServiceReference1.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnits(request);
        }
        
        public webszolg.ServiceReference1.GetCurrencyUnitsResponseBody GetCurrencyUnits(webszolg.ServiceReference1.GetCurrencyUnitsRequestBody GetCurrencyUnits1) {
            webszolg.ServiceReference1.GetCurrencyUnitsRequest inValue = new webszolg.ServiceReference1.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits1;
            webszolg.ServiceReference1.GetCurrencyUnitsResponse retVal = ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetCurrencyUnits(inValue);
            return retVal.GetCurrencyUnitsResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrencyUnitsResponse> webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetCurrencyUnitsAsync(webszolg.ServiceReference1.GetCurrencyUnitsRequest request) {
            return base.Channel.GetCurrencyUnitsAsync(request);
        }
        
        public System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrencyUnitsResponse> GetCurrencyUnitsAsync(webszolg.ServiceReference1.GetCurrencyUnitsRequestBody GetCurrencyUnits) {
            webszolg.ServiceReference1.GetCurrencyUnitsRequest inValue = new webszolg.ServiceReference1.GetCurrencyUnitsRequest();
            inValue.GetCurrencyUnits = GetCurrencyUnits;
            return ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetCurrencyUnitsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webszolg.ServiceReference1.GetCurrentExchangeRatesResponse webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetCurrentExchangeRates(webszolg.ServiceReference1.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRates(request);
        }
        
        public webszolg.ServiceReference1.GetCurrentExchangeRatesResponseBody GetCurrentExchangeRates(webszolg.ServiceReference1.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates1) {
            webszolg.ServiceReference1.GetCurrentExchangeRatesRequest inValue = new webszolg.ServiceReference1.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates1;
            webszolg.ServiceReference1.GetCurrentExchangeRatesResponse retVal = ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRates(inValue);
            return retVal.GetCurrentExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrentExchangeRatesResponse> webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetCurrentExchangeRatesAsync(webszolg.ServiceReference1.GetCurrentExchangeRatesRequest request) {
            return base.Channel.GetCurrentExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<webszolg.ServiceReference1.GetCurrentExchangeRatesResponse> GetCurrentExchangeRatesAsync(webszolg.ServiceReference1.GetCurrentExchangeRatesRequestBody GetCurrentExchangeRates) {
            webszolg.ServiceReference1.GetCurrentExchangeRatesRequest inValue = new webszolg.ServiceReference1.GetCurrentExchangeRatesRequest();
            inValue.GetCurrentExchangeRates = GetCurrentExchangeRates;
            return ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetCurrentExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webszolg.ServiceReference1.GetDateIntervalResponse webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetDateInterval(webszolg.ServiceReference1.GetDateIntervalRequest request) {
            return base.Channel.GetDateInterval(request);
        }
        
        public webszolg.ServiceReference1.GetDateIntervalResponseBody GetDateInterval(webszolg.ServiceReference1.GetDateIntervalRequestBody GetDateInterval1) {
            webszolg.ServiceReference1.GetDateIntervalRequest inValue = new webszolg.ServiceReference1.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval1;
            webszolg.ServiceReference1.GetDateIntervalResponse retVal = ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetDateInterval(inValue);
            return retVal.GetDateIntervalResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetDateIntervalResponse> webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetDateIntervalAsync(webszolg.ServiceReference1.GetDateIntervalRequest request) {
            return base.Channel.GetDateIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<webszolg.ServiceReference1.GetDateIntervalResponse> GetDateIntervalAsync(webszolg.ServiceReference1.GetDateIntervalRequestBody GetDateInterval) {
            webszolg.ServiceReference1.GetDateIntervalRequest inValue = new webszolg.ServiceReference1.GetDateIntervalRequest();
            inValue.GetDateInterval = GetDateInterval;
            return ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetDateIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webszolg.ServiceReference1.GetExchangeRatesResponse webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetExchangeRates(webszolg.ServiceReference1.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRates(request);
        }
        
        public webszolg.ServiceReference1.GetExchangeRatesResponseBody GetExchangeRates(webszolg.ServiceReference1.GetExchangeRatesRequestBody GetExchangeRates1) {
            webszolg.ServiceReference1.GetExchangeRatesRequest inValue = new webszolg.ServiceReference1.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates1;
            webszolg.ServiceReference1.GetExchangeRatesResponse retVal = ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetExchangeRates(inValue);
            return retVal.GetExchangeRatesResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetExchangeRatesResponse> webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetExchangeRatesAsync(webszolg.ServiceReference1.GetExchangeRatesRequest request) {
            return base.Channel.GetExchangeRatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<webszolg.ServiceReference1.GetExchangeRatesResponse> GetExchangeRatesAsync(webszolg.ServiceReference1.GetExchangeRatesRequestBody GetExchangeRates) {
            webszolg.ServiceReference1.GetExchangeRatesRequest inValue = new webszolg.ServiceReference1.GetExchangeRatesRequest();
            inValue.GetExchangeRates = GetExchangeRates;
            return ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetExchangeRatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        webszolg.ServiceReference1.GetInfoResponse webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetInfo(webszolg.ServiceReference1.GetInfoRequest request) {
            return base.Channel.GetInfo(request);
        }
        
        public webszolg.ServiceReference1.GetInfoResponseBody GetInfo(webszolg.ServiceReference1.GetInfoRequestBody GetInfo1) {
            webszolg.ServiceReference1.GetInfoRequest inValue = new webszolg.ServiceReference1.GetInfoRequest();
            inValue.GetInfo = GetInfo1;
            webszolg.ServiceReference1.GetInfoResponse retVal = ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetInfo(inValue);
            return retVal.GetInfoResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<webszolg.ServiceReference1.GetInfoResponse> webszolg.ServiceReference1.MNBArfolyamServiceSoap.GetInfoAsync(webszolg.ServiceReference1.GetInfoRequest request) {
            return base.Channel.GetInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<webszolg.ServiceReference1.GetInfoResponse> GetInfoAsync(webszolg.ServiceReference1.GetInfoRequestBody GetInfo) {
            webszolg.ServiceReference1.GetInfoRequest inValue = new webszolg.ServiceReference1.GetInfoRequest();
            inValue.GetInfo = GetInfo;
            return ((webszolg.ServiceReference1.MNBArfolyamServiceSoap)(this)).GetInfoAsync(inValue);
        }
    }
}
